# Generated by Django 5.1.4 on 2025-01-05 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_customuser_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='items',
        ),
    ]
