# Generated by Django 4.2 on 2025-05-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('User', 'USERS'), ('Seller', 'SELLERS'), ('SuperAdmin', 'SUPERADMIN')], max_length=120, null=True),
        ),
    ]
