# Generated by Django 4.2 on 2025-05-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('User', 'User'), ('Seller', 'Seller'), ('Admin', 'Admin')], max_length=120, null=True),
        ),
    ]
