# Generated by Django 5.1.4 on 2024-12-25 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop_app', '0003_alter_cart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='madified_at',
            new_name='modified_at',
        ),
    ]
